Forced use of user defined variables in config files If user selects to change directories, old data should now be moved automatically if it exists Can change MYSQL_DIR DATA_DIR CONFIG_DIR OC_DIR (probably shouldn't change ownclouds default install path) Fixed cron Fixed update - although if a manual update is required it still errors out as it needs the database to be running, grrr New debug option set ENV DUBUG=TRUE to see what is being executed, set to anything ewlse to be less verbose Now we're using mysql and not mariadb, service folder for database has been renamed

diff --git a/services/nginx/run b/services/nginx/run
--- a/services/nginx/run
+++ b/services/nginx/run
@@ -1,3 +1,23 @@
 #!/usr/bin/with-contenv bash
-exec /usr/sbin/nginx -c /config/nginx/nginx.conf
+run_cmd() {
+    set +e
 
+    cmd=$@
+    if [ "${DEBUG}" == "TRUE" ]
+    then
+        echo "Executing [$cmd]"
+    fi
+    eval $cmd
+    ret_code=$?
+
+    if [ "$ret_code" == "0" ]
+    then
+        echo "$@ executed successfully"
+    else
+        echo "$@ failed with exit code [$ret_code]"
+    fi
+}
+
+echo "Starting nginx webserver service"
+run_cmd "/usr/sbin/nginx -c \"${CONFIG_DIR}/nginx/nginx.conf\""
+echo "Finishing nginx webserver service"
